name       : mtdev
version    : 1.1.5
release    : 7
source     :
    - https://github.com/rydberg/mtdev/archive/v1.1.5.tar.gz : 87c306e5d1822f59a8b69bc9a520fd9f4f7e36ced029d1d98bbaaf11f004d844
license    :
    - MIT
summary    : Multitouch Protocol Translation Library
component  : xorg.driver
description: |
    The mtdev package contains Multitouch Protocol Translation Library which is used to transform all variants of kernel MT (Multitouch) events to the slotted type B protocol.
optimize   :
    - no-symbolic
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
