name       : mtdev
version    : 1.1.5
release    : 6
source     :
    - http://bitmath.org/code/mtdev/mtdev-1.1.5.tar.bz2 : 6677d5708a7948840de734d8b4675d5980d4561171c5a8e89e54adf7a13eba7f
license    :
    - MIT
summary    : Multitouch Protocol Translation Library
component  : xorg.driver
description: |
    The mtdev package contains Multitouch Protocol Translation Library which is used to transform all variants of kernel MT (Multitouch) events to the slotted type B protocol.
optimize   :
    - no-symbolic
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
